[versions]

minecraft-range="1.21"

# Base properties
minecraft_version="1.21"
yarn_mappings="1.21+build.2"
mappings_patch="1.21+build.4"
neoforge="21.0.78-beta"

# Mod properties
version="0.1.0"
maven-group="org.thinkingstudio.forgematica.printer"
archives-name="ForgematicaPrinter"

# Publish properties
id-modrinth="idk"
id-curseforge="idk"

# Mod dependencies
badpackets="neo-0.8.1"
mafglib="0.1.16-mc1.21"
forgematica="0.1.7-mc1.21"

# Gradle plugin
architectury-loom = "1.6-SNAPSHOT"
modpublisher = "2.1.+"

[libraries]
minecraft = { group = "com.mojang", name = "minecraft", version.ref = "minecraft_version" }
yarn-mappings = { group = "net.fabricmc", name = "yarn", version.ref = "yarn_mappings"}
yarn-mappings-patch = { group = "dev.architectury", name = "yarn-mappings-patch-neoforge", version.ref = "mappings_patch"}

neoforge = { group = "net.neoforged", name = "neoforge", version.ref = "neoforge" }

badpackets = { group = "lol.bai", name = "badpackets", version.ref = "badpackets" }
mafglib = { group = "maven.modrinth", name = "mafglib", version.ref = "mafglib"}
forgematica = { group = "maven.modrinth", name = "forgematica", version.ref = "forgematica"}

[plugins]
architectury-loom = { id = "dev.architectury.loom", version.ref = "architectury-loom" }
modpublisher = { id = "com.hypherionmc.modutils.modpublisher", version.ref = "modpublisher" }